trigger:
  branches:
    include:
      - main 
  paths:
    include:
      - user-context-provider/*
    exclude:
      - "*"

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    cd user-context-provider
    npm install
    npm run build
    npm version patch
    npm publish 
  displayName: 'Build and publish npm package'