name: user-context-provider
on:
  push:
    branches:
      - main
    paths:
      - "user-context-provider/**"

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Clean up Repo
        run: sudo rm -rf "/home/azureuser/actions-runner/_work/RapidX/RapidX/RapidX"
      - name: Check Out Repo
        uses: actions/checkout@v2      
      - name: Checkout to that folder
        run: cd user-context-provider
      - name: Install the dependencies
        run: npm install
      - name: Build the library
        run: npm run build
      - name: Publish the package to azure artifacts
        run: npm publish